import Foundation

/// The stable coordinate map used by the weekly anatomy view.
/// Coordinates are normalized inside the separately rendered front/back image
/// assets. Keeping the coordinate space panel-local means the UI never has to
/// crop or offset the original combined SVG at runtime.
public enum MuscleMapPanel: String, CaseIterable, Codable, Sendable {
    case front
    case back
    case list
}

public enum MuscleMapCalloutSide: String, Codable, Hashable, Sendable {
    case left
    case right
}

public struct MuscleMapCallout: Equatable, Hashable, Sendable, Identifiable {
    public let group: MuscleGroup
    public let panel: MuscleMapPanel
    public let anchorX: Double
    public let anchorY: Double
    public let side: MuscleMapCalloutSide

    public var id: String { "\(panel.rawValue)-\(group.rawValue)" }

    public init(group: MuscleGroup,
                panel: MuscleMapPanel,
                anchorX: Double,
                anchorY: Double,
                side: MuscleMapCalloutSide) {
        self.group = group
        self.panel = panel
        self.anchorX = anchorX
        self.anchorY = anchorY
        self.side = side
    }
}

/// The map uses the fixed pixel dimensions of the bundled, transparent
/// front/back PNG assets. Each anchor is normalized within its selected panel,
/// and its side determines which outside label column owns the connector.
public enum MuscleMapLayout {
    public static let panelPixelWidth = 1024.0
    public static let panelPixelHeight = 1782.0
    public static let panelRatio = panelPixelWidth / panelPixelHeight

    public static let callouts: [MuscleMapCallout] = [
        // Front-visible groups.
        .init(group: .neck, panel: .front, anchorX: 0.46, anchorY: 0.17, side: .left),
        .init(group: .shoulders, panel: .front, anchorX: 0.32, anchorY: 0.23, side: .left),
        .init(group: .biceps, panel: .front, anchorX: 0.28, anchorY: 0.34, side: .left),
        .init(group: .hipFlexors, panel: .front, anchorX: 0.42, anchorY: 0.50, side: .left),
        .init(group: .abductors, panel: .front, anchorX: 0.35, anchorY: 0.48, side: .left),
        .init(group: .quadriceps, panel: .front, anchorX: 0.41, anchorY: 0.65, side: .left),
        .init(group: .tibialis, panel: .front, anchorX: 0.43, anchorY: 0.80, side: .left),
        .init(group: .chest, panel: .front, anchorX: 0.58, anchorY: 0.29, side: .right),
        .init(group: .abdominals, panel: .front, anchorX: 0.58, anchorY: 0.39, side: .right),
        .init(group: .forearms, panel: .front, anchorX: 0.78, anchorY: 0.45, side: .right),
        .init(group: .adductors, panel: .front, anchorX: 0.54, anchorY: 0.54, side: .right),
        .init(group: .calves, panel: .front, anchorX: 0.55, anchorY: 0.78, side: .right),

        // Back-visible groups.
        .init(group: .neck, panel: .back, anchorX: 0.48, anchorY: 0.16, side: .left),
        .init(group: .shoulders, panel: .back, anchorX: 0.34, anchorY: 0.24, side: .left),
        .init(group: .triceps, panel: .back, anchorX: 0.31, anchorY: 0.35, side: .left),
        .init(group: .lats, panel: .back, anchorX: 0.40, anchorY: 0.37, side: .left),
        .init(group: .abductors, panel: .back, anchorX: 0.40, anchorY: 0.47, side: .left),
        .init(group: .hamstrings, panel: .back, anchorX: 0.45, anchorY: 0.62, side: .left),
        .init(group: .traps, panel: .back, anchorX: 0.56, anchorY: 0.24, side: .right),
        .init(group: .rotatorCuff, panel: .back, anchorX: 0.66, anchorY: 0.29, side: .right),
        .init(group: .middleBack, panel: .back, anchorX: 0.56, anchorY: 0.34, side: .right),
        .init(group: .forearms, panel: .back, anchorX: 0.76, anchorY: 0.44, side: .right),
        .init(group: .lowerBack, panel: .back, anchorX: 0.56, anchorY: 0.46, side: .right),
        .init(group: .glutes, panel: .back, anchorX: 0.56, anchorY: 0.51, side: .right),
        .init(group: .calves, panel: .back, anchorX: 0.59, anchorY: 0.80, side: .right)
    ]

    /// The groups that have a colour mask on each anatomy panel, generated by
    /// `scripts/generate-muscle-masks.py` from the artwork's own muscle
    /// outlines. This is a superset of the callouts: a muscle that is visible
    /// on a panel is coloured there even when its tap target lives on the
    /// other panel (e.g. the upper trapezius seen from the front, or the
    /// medial triceps between biceps and armpit).
    public static func maskGroups(for panel: MuscleMapPanel) -> [MuscleGroup] {
        switch panel {
        case .front:
            [.abdominals, .abductors, .adductors, .biceps, .calves, .chest, .forearms,
             .hipFlexors, .neck, .quadriceps, .shoulders, .tibialis, .traps, .triceps]
        case .back:
            [.abdominals, .abductors, .adductors, .calves, .forearms, .glutes, .hamstrings,
             .lats, .lowerBack, .middleBack, .neck, .quadriceps, .rotatorCuff, .shoulders,
             .traps, .triceps]
        case .list:
            []
        }
    }

    /// Mask groups shown for the current volume scope, mirroring
    /// `callouts(for:visibleGroups:)` so the colour and the tap targets agree.
    public static func maskGroups(for panel: MuscleMapPanel,
                                  visibleGroups: Set<MuscleGroup>) -> [MuscleGroup] {
        maskGroups(for: panel).filter { visibleGroups.contains($0) }
    }

    /// Masks drawn solid white under the group colours, so the map never shows the artwork's red
    /// on muscle that no workout can turn green: the panel's untracked anatomy (head, hands, feet)
    /// and every mask group outside the current volume scope (e.g. neck, tibialis, rotator cuff
    /// when they aren't tracked).
    public static func neutralMaskAssetNames(for panel: MuscleMapPanel,
                                             visibleGroups: Set<MuscleGroup>) -> [String] {
        guard panel != .list else { return [] }
        return [untrackedMaskAssetName(for: panel)]
            + maskGroups(for: panel).filter { !visibleGroups.contains($0) }
                .map { maskAssetName(for: $0, panel: panel) }
    }

    /// Asset-catalog name of a panel's untracked-anatomy mask.
    public static func untrackedMaskAssetName(for panel: MuscleMapPanel) -> String {
        "MuscleMask-\(panel.rawValue)-untracked"
    }

    /// Asset-catalog name of a group's colour mask on a panel.
    public static func maskAssetName(for group: MuscleGroup, panel: MuscleMapPanel) -> String {
        "MuscleMask-\(panel.rawValue)-\(group.rawValue)"
    }

    /// The panel that best shows a group on its own (its callout's panel), used
    /// by single-muscle thumbnails.
    public static func primaryPanel(for group: MuscleGroup) -> MuscleMapPanel {
        callouts.first { $0.group == group }?.panel ?? .front
    }

    public static func callouts(for panel: MuscleMapPanel) -> [MuscleMapCallout] {
        callouts.filter { $0.panel == panel }
    }

    /// Returns only the callouts represented by a volume surface. The anatomy
    /// artwork contains all 20 DB++ groups, while Home deliberately hides an
    /// untracked group until it has credited work. Keeping this filter here
    /// prevents the graphic and the list from presenting different scopes.
    public static func callouts(for panel: MuscleMapPanel,
                                visibleGroups: Set<MuscleGroup>) -> [MuscleMapCallout] {
        callouts(for: panel).filter { visibleGroups.contains($0.group) }
    }
}
