import XCTest
@testable import CadenceCore
#if canImport(ImageIO)
import CoreGraphics
import ImageIO
#endif

/// Guards the Home muscle map's colour masks (generated by
/// `scripts/generate-muscle-masks.py`) against the regressions the field test
/// found: a tracked group with no colour at all, a mask that only covers part
/// of its muscle, a mask drawn over the wrong muscle, and two groups claiming
/// the same pixels.
final class MuscleMapMaskAssetTests: XCTestCase {
    func testEveryTrackedGroupIsColouredOnAtLeastOnePanel() {
        let coloured = Set(MuscleMapLayout.maskGroups(for: .front) + MuscleMapLayout.maskGroups(for: .back))
        XCTAssertEqual(coloured, Set(MuscleGroup.allCases))
        XCTAssertTrue(MuscleMapLayout.maskGroups(for: .list).isEmpty)
    }

    func testEveryCalloutIsColouredOnItsOwnPanel() {
        for callout in MuscleMapLayout.callouts {
            XCTAssertTrue(MuscleMapLayout.maskGroups(for: callout.panel).contains(callout.group),
                          "\(callout.id) has a tap target but no colour mask")
        }
        for group in MuscleGroup.allCases {
            let panel = MuscleMapLayout.primaryPanel(for: group)
            XCTAssertTrue(MuscleMapLayout.maskGroups(for: panel).contains(group), group.rawValue)
        }
    }

    func testVisibleMaskGroupsFollowTheVolumeScope() {
        let visible = MuscleMapLayout.maskGroups(for: .back, visibleGroups: MuscleGroup.defaultTracked)
        XCTAssertFalse(visible.contains(.rotatorCuff))
        XCTAssertTrue(visible.contains(.lats))
    }

    /// Field report 2026-10-04: with every group on target, untracked muscle (head, hands, feet,
    /// and groups outside the volume scope such as neck, tibialis and rotator cuff) still showed
    /// the artwork's red. It is drawn white instead.
    func testNeutralMasksAreTheUntrackedAnatomyPlusEveryHiddenGroup() {
        let visible = MuscleGroup.defaultTracked
        for panel in [MuscleMapPanel.front, .back] {
            let names = MuscleMapLayout.neutralMaskAssetNames(for: panel, visibleGroups: visible)
            XCTAssertEqual(names.first, MuscleMapLayout.untrackedMaskAssetName(for: panel))
            let hidden = MuscleMapLayout.maskGroups(for: panel).filter { !visible.contains($0) }
            XCTAssertEqual(Set(names.dropFirst()),
                           Set(hidden.map { MuscleMapLayout.maskAssetName(for: $0, panel: panel) }))
            let coloured = MuscleMapLayout.maskGroups(for: panel, visibleGroups: visible)
            XCTAssertTrue(coloured.allSatisfy {
                !names.contains(MuscleMapLayout.maskAssetName(for: $0, panel: panel))
            }, "a group is never both coloured and neutral")
        }
        XCTAssertTrue(MuscleMapLayout.neutralMaskAssetNames(for: .back, visibleGroups: visible)
            .contains(MuscleMapLayout.maskAssetName(for: .rotatorCuff, panel: .back)))
        XCTAssertTrue(MuscleMapLayout.neutralMaskAssetNames(for: .front, visibleGroups: visible)
            .contains(MuscleMapLayout.maskAssetName(for: .tibialis, panel: .front)))
        XCTAssertEqual(MuscleMapLayout.neutralMaskAssetNames(for: .front, visibleGroups: Set(MuscleGroup.allCases)),
                       [MuscleMapLayout.untrackedMaskAssetName(for: .front)])
    }

    #if canImport(ImageIO)
    func testAssetCatalogHoldsExactlyTheListedMasks() throws {
        let names = try FileManager.default.contentsOfDirectory(atPath: Self.assetCatalog.path)
            .filter { $0.hasPrefix("MuscleMask-") && $0.hasSuffix(".imageset") }
            .map { String($0.dropLast(".imageset".count)) }
        let expected = [MuscleMapPanel.front, .back].flatMap { panel in
            MuscleMapLayout.maskGroups(for: panel).map { MuscleMapLayout.maskAssetName(for: $0, panel: panel) }
                + [MuscleMapLayout.untrackedMaskAssetName(for: panel)]
        }
        XCTAssertEqual(Set(names), Set(expected))
    }

    /// Loads every mask once (decoding PNGs is the slow part) and checks that
    /// each one is a full-size, non-empty region; that each callout sits on
    /// its own muscle; and that every red muscle pixel anywhere on the panel
    /// (head, neck, hands and feet included) belongs to exactly one mask, a
    /// group's or the white untracked mask, so with every group on target no
    /// red remains, no tracked muscle is partly coloured, and no two masks
    /// colour the same pixel.
    func testMasksAreCompleteAlignedAndDisjoint() throws {
        let width = Int(MuscleMapLayout.panelPixelWidth)
        let height = Int(MuscleMapLayout.panelPixelHeight)
        for panel in [MuscleMapPanel.front, .back] {
            var owners = [UInt8](repeating: 0, count: width * height)
            var totalCovered = 0
            for group in MuscleMapLayout.maskGroups(for: panel) {
                let name = MuscleMapLayout.maskAssetName(for: group, panel: panel)
                let mask = try Self.render(name, alphaOnly: true)
                XCTAssertEqual(mask.width, width, name)
                XCTAssertEqual(mask.height, height, name)
                guard mask.width == width, mask.height == height else { continue }
                let covered = Self.accumulate(mask.bytes, into: &owners)
                totalCovered += covered
                XCTAssertGreaterThan(covered, 2_000, "\(name) is (nearly) uncoloured")
                for callout in MuscleMapLayout.callouts(for: panel) where callout.group == group {
                    let x = Int((callout.anchorX * Double(width)).rounded())
                    let y = Int((callout.anchorY * Double(height)).rounded())
                    // Outline strokes are left uncoloured, so an anchor may sit
                    // on a stroke; it must touch its own colour within 4 px.
                    let onMuscle = (-4...4).contains { dy in
                        (-4...4).contains { dx in mask.bytes[(y + dy) * width + x + dx] > 0 }
                    }
                    XCTAssertTrue(onMuscle, "\(callout.id) anchor is not on its own muscle")
                }
            }

            let untrackedName = MuscleMapLayout.untrackedMaskAssetName(for: panel)
            let untracked = try Self.render(untrackedName, alphaOnly: true)
            XCTAssertEqual(untracked.bytes.count, width * height, untrackedName)
            if untracked.bytes.count == width * height {
                XCTAssertGreaterThan(Self.accumulate(untracked.bytes, into: &owners), 2_000,
                                     "\(untrackedName) should cover the head, hands and feet")
            }

            let art = try Self.render(panel == .front ? "MuscleMapFront" : "MuscleMapBack",
                                      alphaOnly: false)
            let (uncovered, overlapping) = art.bytes.withUnsafeBufferPointer { rgba in
                owners.withUnsafeBufferPointer { owners in
                    var uncovered = 0, overlapping = 0
                    for y in 0..<height {
                        for x in 0..<width {
                            let count = owners[y * width + x]
                            if count > 1 { overlapping += 1 }
                            guard count == 0 else { continue }
                            if Self.isMuscle(rgba, index: (y * width + x) * 4) { uncovered += 1 }
                        }
                    }
                    return (uncovered, overlapping)
                }
            }
            XCTAssertEqual(art.bytes.count, width * height * 4, "\(panel) artwork did not load")
            XCTAssertGreaterThan(totalCovered, 200_000, "\(panel) masks colour too little of the body")
            XCTAssertEqual(uncovered, 0, "\(panel): \(uncovered) red muscle pixels are covered by no mask")
            XCTAssertEqual(overlapping, 0, "\(panel): \(overlapping) pixels are coloured by two groups")
        }
    }

    // MARK: - Asset loading

    private struct Bitmap {
        let width: Int
        let height: Int
        /// One alpha byte per pixel, or premultiplied RGBA (4 bytes per pixel).
        let bytes: [UInt8]
    }

    private struct MissingAsset: Error {
        let path: String
    }

    private static var assetCatalog: URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent() // CadenceCoreTests
            .deletingLastPathComponent() // Tests
            .deletingLastPathComponent() // CadenceCore
            .deletingLastPathComponent() // repository
            .appendingPathComponent("Cadence/Cadence/Assets.xcassets")
    }

    private static func render(_ name: String, alphaOnly: Bool) throws -> Bitmap {
        let url = assetCatalog.appendingPathComponent("\(name).imageset/\(name).png")
        guard let source = CGImageSourceCreateWithURL(url as CFURL, nil),
              let image = CGImageSourceCreateImageAtIndex(source, 0, nil) else {
            throw MissingAsset(path: url.path)
        }
        let width = image.width, height = image.height
        let channels = alphaOnly ? 1 : 4
        // Draw in the PNG's own colour space so the artwork's red values are
        // not colour-converted before the muscle rule reads them.
        let colorSpace: CGColorSpace? = alphaOnly ? nil
            : image.colorSpace.flatMap { $0.model == .rgb ? $0 : nil } ?? CGColorSpace(name: CGColorSpace.sRGB)
        let info = alphaOnly ? CGImageAlphaInfo.alphaOnly : .premultipliedLast
        var bytes = [UInt8](repeating: 0, count: width * height * channels)
        let drawn = bytes.withUnsafeMutableBytes { buffer -> Bool in
            guard let context = CGContext(data: buffer.baseAddress, width: width, height: height,
                                          bitsPerComponent: 8, bytesPerRow: width * channels,
                                          space: colorSpace ?? CGColorSpaceCreateDeviceGray(),
                                          bitmapInfo: info.rawValue) else {
                return false
            }
            context.draw(image, in: CGRect(x: 0, y: 0, width: width, height: height))
            return true
        }
        XCTAssertTrue(drawn, name)
        return Bitmap(width: width, height: height, bytes: bytes)
    }

    /// Adds one owner to every pixel the mask covers and returns how many it
    /// covers. Masks are mostly empty, so whole zero words are skipped.
    private static func accumulate(_ alpha: [UInt8], into owners: inout [UInt8]) -> Int {
        alpha.withUnsafeBytes { alphaBytes in
            owners.withUnsafeMutableBufferPointer { owners in
                let words = alphaBytes.count / 8
                var covered = 0
                for word in 0..<words where alphaBytes.loadUnaligned(fromByteOffset: word * 8, as: UInt64.self) != 0 {
                    for index in word * 8..<word * 8 + 8 where alphaBytes[index] != 0 {
                        owners[index] &+= 1
                        covered += 1
                    }
                }
                for index in words * 8..<alphaBytes.count where alphaBytes[index] != 0 {
                    owners[index] &+= 1
                    covered += 1
                }
                return covered
            }
        }
    }

    /// The artwork's red muscle fill (same rule as the generator's `is_muscle`).
    private static func isMuscle(_ rgba: UnsafeBufferPointer<UInt8>, index: Int) -> Bool {
        let alpha = Int(rgba[index + 3])
        guard alpha > 100 else { return false }
        // Un-premultiply so the colour rule matches the source PNG values.
        let red = Int(rgba[index]) * 255 / alpha
        let green = Int(rgba[index + 1]) * 255 / alpha
        let blue = Int(rgba[index + 2]) * 255 / alpha
        return red > 120 && red * 2 > green * 3 && red * 2 > blue * 3
            && green < 120 && blue < 120 && red - green > 80
    }
    #endif
}
